# Generated by Django 5.2.10 on 2026-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_bench', models.CharField(blank=True, max_length=100, verbose_name='Assigned Bench')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Supplier')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='QTY')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('storage_location', models.CharField(blank=True, max_length=100, verbose_name='Storage Location')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
                'ordering': ['assigned_bench', 'type', 'supplier'],
            },
        ),
    ]
