# Generated by Django 6.0.1 on 2026-02-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('WORKING', 'Working'), ('LEND', 'Lend'), ('DAMAGE', 'Damaged')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(choices=[('APTIV', 'Aptiv'), ('VECTOR', 'Vector'), ('LAUTERBACH', 'Lauterbach'), ('DELL', 'Dell'), ('VALLEY_INT', 'Valley Int')], max_length=30, verbose_name='Supplier'),
        ),
    ]
