# Generated by Django 6.0.1 on 2026-02-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_inventoryitem_qty_alter_inventoryitem_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['id', 'assigned_bench', 'type', 'supplier'], 'verbose_name': 'Inventory item', 'verbose_name_plural': 'Inventory items'},
        ),
    ]
