# Generated by Django 6.0.1 on 2026-02-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_inventoryitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='assigned_bench',
            field=models.CharField(choices=[('L21', 'CADMsL2+_1'), ('L22', 'CADMsL2+_2'), ('LO1', 'CADMSLo_1')], max_length=30, verbose_name='Assigned Bench'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('WORKING', 'Working'), ('LEND', 'Lend'), ('DAMAGE', 'Damaged')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(choices=[('BENCH', 'Bench Desk'), ('GABINET', 'Gabinet 1'), ('NA', 'N/A')], max_length=20, verbose_name='Storage Location'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.CharField(choices=[('BENCH', 'Bench equipment'), ('LICENSE', 'License'), ('HARNESS', 'Harness'), ('RADAR', 'Radar'), ('CAMERA', 'Camera'), ('ECU', 'ECU'), ('OTHER', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
