# Generated by Django 5.2.10 on 2026-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_inventoryitem_assigned_bench_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='calibration_date',
            field=models.DateField(auto_now=True, verbose_name='Calibration Date'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='certification_date',
            field=models.DateField(auto_now=True, verbose_name='Certification Date'),
        ),
    ]
