# Generated by Django 6.0.1 on 2026-02-06 16:22

from django.db import migrations

def forwards(apps, schema_editor):
    InventoryItem = apps.get_model("inv", "InventoryItem")
    AssignedBench = apps.get_model("inv", "AssignedBench")
    ItemType = apps.get_model("inv", "ItemType")
    Supplier = apps.get_model("inv", "Supplier")
    Status = apps.get_model("inv", "Status")
    StorageLocation = apps.get_model("inv", "StorageLocation")

    bench_labels = {"L21": "CADMsL2+_1", "L22": "CADMsL2+_2", "LO1": "CADMSLo_1"}
    type_labels = { 
        "BENCH": "Bench equipment", "LICENSE": "License", "HARNESS": "Harness",
        "RADAR": "Radar", "CAMERA": "Camera", "ECU": "ECU", "OTHER": "Other"
    }
    supplier_labels = {
        "APTIV": "Aptiv", "VECTOR": "Vector", "LAUTERBACH": "Lauterbach",
        "DELL": "Dell", "VALLEY_INT": "Valley Int"
    }
    status_labels = {"WORKING": "Working", "LEND": "Lend", "DAMAGE": "Damaged"}
    storage_labels = {"BENCH": "Bench Desk", "GABINET": "Gabinet 1", "NA": "N/A"}

    for it in InventoryItem.objects.all():
        if it.assigned_bench:
            b, _ = AssignedBench.objects.get_or_create(
                code=it.assigned_bench, defaults={"label": bench_labels.get(it.assigned_bench, "")}
            )
            it.assigned_bench_fk = b
        
        if it.type:
            t, _ = ItemType.objects.get_or_create(
                code=it.type, defaults={"label": type_labels.get(it.type, "")}
            )
            it.type_fk = t

        if it.supplier:
            s, _ = Supplier.objects.get_or_create(
                code=it.supplier, defaults={"label": supplier_labels.get(it.supplier, "")}
            )
            it.supplier_fk = s

        if it.status:
            st, _ = Status.objects.get_or_create(
                code=it.status, defaults={"label": status_labels.get(it.status, "")}
            )
            it.status_fk = st

        if it.storage_location:
            sl, _ = StorageLocation.objects.get_or_create(
                code=it.storage_location, defaults={"label": storage_labels.get(it.storage_location, "")}
            )
            it.storage_location_fk = sl
        it.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_assignedbench_itemtype_status_storagelocation_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
