# Generated by Django 6.0.1 on 2026-02-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_move_choices_to_catalogs'),
    ]

    operations = [
        migrations.RemoveField(model_name="inventoryitem", name="assigned_bench"),
        migrations.RemoveField(model_name="inventoryitem", name="type"),
        migrations.RemoveField(model_name="inventoryitem", name="supplier"),
        migrations.RemoveField(model_name="inventoryitem", name="status"),
        migrations.RemoveField(model_name="inventoryitem", name="storage_location"),
        
        migrations.RenameField(model_name="inventoryitem", old_name="assigned_bench_fk", new_name="assigned_bench"),
        migrations.RenameField(model_name="inventoryitem", old_name="type_fk", new_name="type"),
        migrations.RenameField(model_name="inventoryitem", old_name="supplier_fk", new_name="supplier"),
        migrations.RenameField(model_name="inventoryitem", old_name="status_fk", new_name="status"),
        migrations.RenameField(model_name="inventoryitem", old_name="storage_location_fk", new_name="storage_location"),
    ]
