# Generated by Django 6.0.1 on 2026-02-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_finalize_catalog_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapexOpex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Asset #'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cft_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CFT #'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Invoice ID'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PO #'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pr_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PR #'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Serial #'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='wo_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='WO'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='assigned_bench',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.assignedbench'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.storagelocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inv.itemtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='capex_opex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.capexopex'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.ownerteam'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.project'),
        ),
    ]
