# Generated by Django 6.0.1 on 2026-02-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_create_admin_group'),
        ('inv', '0008_capexopex_ownerteam_project_and_more'),
    ]

    operations = [
    ]
