# Generated by Django 6.0.1 on 2026-02-11 21:12

import django.db.models.deletion
import django.utils.timezone
import inv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_merge_20260210_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='owner_team',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='calibration_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='certification_date',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requires_certification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='capexopex',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='capexopex',
            name='label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='assigned_bench',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.assignedbench'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.status'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.storagelocation'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.supplier'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.itemtype'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateField(default=django.utils.timezone.localdate)),
                ('file', models.FileField(upload_to=inv.models.certification_upload_to)),
                ('year', models.PositiveIntegerField(editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='inv.inventoryitem')),
            ],
            options={
                'ordering': ['-certification_date'],
            },
        ),
        migrations.DeleteModel(
            name='OwnerTeam',
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['item', 'certification_date'], name='inv_certifi_item_id_1f0aee_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['year'], name='inv_certifi_year_5cbf55_idx'),
        ),
    ]
